Implement name filtering
phaazon/toodoux pull request #54
Opened 2020-11-01 22:13 UTC by DarkDrek

Implements #51 

Here a few questions / remarks that may be need to be discussed:

- This is case-sensitive so "Do" and "do" would be two different words.
- There is no explanation header to describe whats filtered like for the priority [ +Critical ]
  - May be something like [ Contains: A, B ] could work?

2020-11-02 16:52 UTC, phaazon commented
Hello! Thanks for the contribution!

> This is case-sensitive so "Do" and "do" would be two different words.

I think we could config-flag this behavior.

> There is no explanation header to describe whats filtered like for the priority [ +Critical ]
>    May be something like [ Contains: A, B ] could work?

Yep, I like the idea to add a `contains: …` hint!

2020-11-02 17:02 UTC, phaazon requested changes
One single nit but the rest is fine. Thanks! :+1:

2020-11-02 17:02 UTC, phaazon commented on src/cli.rs
> +        name_filter.is_empty()
I think you can simply replace all this with 
```suggestion
        for word in task.name().split_ascii_whitespace() { 
          let _ = name_filter.remove(word);
         
          if name_filter.is_empty() {
            return true;
          }
        }
        
        return false;
```

The fact that the word is found is not really important: what is important is the state of the `HashSet`. If it’s empty, it means that we have found everything and we can short-circuit and leave. Given that, if the control flow exits the `for`, then we have still something in the `HashSet` and we then the test is failed.

2020-11-02 18:01 UTC, DarkDrek commented on src/cli.rs
> +        name_filter.is_empty()
The early return is fine but the `word_found` is actually a small optimization because if [remove](https://doc.rust-lang.org/std/collections/struct.HashSet.html#method.remove) returns false the set isn't modified and we do not need to check the set. But it may not matter because isEmpty should be inlined and a simple value access.

2020-11-02 18:02 UTC, DarkDrek commented
> Hello! Thanks for the contribution!
> 
> > This is case-sensitive so "Do" and "do" would be two different words.
> 
> I think we could config-flag this behavior.
> 
> > There is no explanation header to describe whats filtered like for the priority [ +Critical ]
> > May be something like [ Contains: A, B ] could work?
> 
> Yep, I like the idea to add a `contains: …` hint!

Do you want new issues for both of these features?

2020-11-02 21:48 UTC, DarkDrek commented on src/cli.rs
> +        name_filter.is_empty()
The early return part is pushed.

2020-11-03 10:57 UTC, phaazon commented
> > Hello! Thanks for the contribution!
> > > This is case-sensitive so "Do" and "do" would be two different words.
> > 
> > 
> > I think we could config-flag this behavior.
> > > There is no explanation header to describe whats filtered like for the priority [ +Critical ]
> > > May be something like [ Contains: A, B ] could work?
> > 
> > 
> > Yep, I like the idea to add a `contains: …` hint!
> 
> Do you want new issues for both of these features?

You don’t have to mind them, I will create them.

2020-11-03 10:57 UTC, phaazon approved these changes

2020-11-03 10:57 UTC, merged