Display tags column
phaazon/toodoux pull request #58
Opened 2020-11-03 21:08 UTC by DarkDrek

Implements #38 

This just reserves enough space to display all tag values which may not work when there are a lot of tags.
In a previous commit a had a simple logic to just display ... after the end of the space was reached but I'm not sure if that is the right approach?

2020-11-07 22:57 UTC, DarkDrek commented
I've rebased it.

2020-11-16 00:42 UTC, phaazon requested changes

2020-11-16 00:42 UTC, phaazon commented on src/cli.rs
> +        has_tags,
This is just a note for myself: I really think we should get rid of this huge fold accumulator and use a data type. It’s becoming hard to follow what is what. :D

2020-11-16 00:42 UTC, phaazon commented on src/cli.rs
> +      .sum()
I’m not a huge fan of this — we’re going to allocate several time / recompute several times the same string. I think we should move away from doing things this way.

2020-11-16 00:42 UTC, phaazon commented on src/cli.rs
> +    tags = task.tags().intersperse(", ").collect::<String>(),
Same remark as above.

2020-11-16 18:04 UTC, LordMZTE commented on src/cli.rs
> +        has_tags,
yeah ive had some trouble understanding that before

2020-11-16 18:06 UTC, LordMZTE commented on src/cli.rs
> +      .sum()
this could be solved by summing up the width of all tags, and then adding the width of the separator `n-1` times

2021-01-18 18:05 UTC, phaazon commented
As with #59, I’ll take it over. Thanks!

2021-01-19 00:04 UTC, merged